default[:apts3][:access_id] = ""
default[:apts3][:secret_key] = ""
default[:apts3][:components] = ""
default[:apts3][:bucket] = ""
default[:apts3][:architectures] = ""
default[:apts3][:distribution] = ""
